//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGUSRPLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiGUSRPLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:ns=&quot;http://CIS/BIR/PUBL/2014/07&quot; xmlns:dat=&quot;http://CIS/BIR/PUBL/2014/07/DataContract&quot;&gt;
        ///  &lt;soap:Header xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot; xmlns:wsrm=&quot;http://docs.oasis-open.org/ws-rx/wsrm/200702&quot;&gt;
        ///    &lt;wsrm:Sequence&gt;
        ///      &lt;wsrm:Identifier&gt;
        ///        s:Sender
        ///
        ///        a:ActionNotSupported
        ///      &lt;/wsrm:Identifier&gt;
        ///      &lt;wsrm:MessageNumber&gt;1&lt;/wsrm:MessageNumber&gt;
        ///    &lt;/wsrm:Sequence&gt;
        ///    &lt;wsa:Action&gt;http://CIS/BIR/P [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Szukaj {
            get {
                return ResourceManager.GetString("Szukaj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:ns=&quot;http://CIS/BIR/PUBL/2014/07&quot;&gt;
        ///  &lt;soap:Header xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot; xmlns:wsrm=&quot;http://docs.oasis-open.org/ws-rx/wsrm/200702&quot;&gt;
        ///    &lt;wsrm:Sequence&gt;
        ///      &lt;wsrm:Identifier&gt;
        ///        s:Sender
        ///
        ///        a:ActionNotSupported
        ///      &lt;/wsrm:Identifier&gt;
        ///      &lt;wsrm:MessageNumber&gt;1&lt;/wsrm:MessageNumber&gt;
        ///    &lt;/wsrm:Sequence&gt;
        ///    &lt;wsa:Action&gt;http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj&lt;/wsa:Action&gt;
        /// [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Wyloguj {
            get {
                return ResourceManager.GetString("Wyloguj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:ns=&quot;http://CIS/BIR/PUBL/2014/07&quot;&gt;
        ///  &lt;soap:Header xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot; xmlns:wsrm=&quot;http://docs.oasis-open.org/ws-rx/wsrm/200702&quot;&gt;
        ///    &lt;wsrm:Sequence&gt;
        ///      &lt;wsrm:Identifier&gt;
        ///        s:Sender
        ///
        ///        a:ActionNotSupported
        ///      &lt;/wsrm:Identifier&gt;
        ///      &lt;wsrm:MessageNumber&gt;1&lt;/wsrm:MessageNumber&gt;
        ///    &lt;/wsrm:Sequence&gt;
        ///    &lt;wsa:Action&gt;http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj&lt;/wsa:Action&gt;
        /// [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Zaloguj {
            get {
                return ResourceManager.GetString("Zaloguj", resourceCulture);
            }
        }
    }
}
